language: python

python:
- 3.6

services:
  - docker

env:
  matrix:
  - TOXENV="py${PYTHON_VERSION//./}"
  global:
    # DOCKER_USERNAME
    - secure: "lBni6uQw7CAY85jiBmTWExNqdoUdEkuMYO4CN7j6nsfUKihGDVIUE6kWNQh3O/NHla8Gygvj2Ksq7Iu1Tmh7em99DFKyi66XscRXuABygJwrm6Rbz9N3p2suYkGV+hR61xwhcOukrNnxoM16K8pRIvQxBtpecsouT9LNF0Rw8xQho1GS391I6F9LcSGpHjGNNCx3LBbMuNa7/qLe+JZCERGCYesJO1suQPP5CBX0Bykv/mpzUq0yRQW/HCGoZzGzYJduP/0ewQERWzemMBMYdFjfwb6Z+Rx5tuVUJ3ttTU8bc/08K2D3jrCjjRTUCxHMDMZpGMhZEq2o7x7+Th6PxkLjYyo5aF3GvngzRZSSyIJSooXcgmNLiXUk0k3+udcBMo4neYKaV12JFC3/N5nXAI6vNAA6nE1x++rqlCNTcy2d4BQBYAyyvx7wkLmVl+dBTQNppzBzwqkruhkYjcKO6KERipbFqc1s8MBY0PeorsUHYSMuJVuPzyCb2LkykTYH9VeyG6tswwT0ZTqDuOl1uP/TycHZfizCJ2jD4F+5w9p1CNFnZj89p7z8BNVa1k83U8rQPQpgvz7pPy+6XxU8QINQeySRsu5D9aY+HA8zHOJBKNHy7YJA4HsdgrRCl2XU626YjBje+e9nrQsY1FL+XTgXx0Qpspwo6klkqEYPonc="
    # DOCKER_PASSWORD
    - secure: "sGQtb8DVFI9ZAW6rgMSsUVWECVbK039q8DkDbc+2MYkGCJlFcTnhw5ttcq9N73dnRefdDLc7wR4RcHjoUx5XB2b/eUzJydov3IFHxPvedwLm5/3rLJUuHdkJgvooTc6tzA7OMDtUBG9PouBsj+ulnIT1dRx/MVuXu7GxNfZh67PgPnmsXhkI45gYtpujcHCUi/Cvx2h2W9xzjz8Nf3/Mdnp5cMKFGBFxaFuqIto+pdHcDkJlT1oT3pESc58cnnxHG61ePFfJpS0OaYPoBEIrT0rEng29TUM2DaA1qN2ELzG2rtEhcFQ9azKK81gako6Tp9lcnpu6TK02wiReKsnuPiMwVtLRSdcfF7jTaEc9KEQ2m5Gof+LQP+3u72h5NnmJs1JuPP63h7mE72Zc9Ds9/uwukhomdzs0Wku99294hhQvf/xsO+LHtnNUgjssSn1+sMeuwrcPcTHsRGaorO7nDGd/cm3jslPlKXAGf3lxystmCbxKOzvxhCUpoXHLIVsLq3ALMxWDBLJjfBeCjEe9g3Jb2qMbx6LLufnTjM06EFvVlLBp0Yu2HgEIXyVhk1l5W4adbvsE5s/PrM1IeOFn9S4p8ouMY3lP4dkKrIgJzMbMTBKCRhb7+72hZ1RNaVcxv9qV1YTs+ke6dzHQtb/zMwDr0otkwipSq3P1OEldxMQ="

install:
- pip install tox coveralls

script: tox

after_success:
- coveralls

deploy:
- provider: script
  script: make ci-push
  on:
    branch: master
