language: python

python:
- 3.6

services:
  - docker

env:
  matrix:
  - TOXENV="py${PYTHON_VERSION//./}"
  global:
    # DOCKER_USERNAME
    secure: "klL6Spu6FSBKzlBHP/jK5jFvbVhnclC5TH5kyQXZlwqUvRIGD0AVS5DLOlBlDJ/NYECP4/p7SW7DmX5rJBft/pJfVFIM3EWEAH9Uzn0ojJPjGgOCyRolM+jlSQa91hJuG2aYYfFtDnR8+wH0vCOMPCaSklxl7i/l+v2b85XvqgVDAALW4h2JLgqBUqkmu2LD2BSfdW8xFZ5Oeei7fslF1SNASBvsZI9unXsBoeEGSffhqSf/A94Q43gfCX4ZLH6CNnHL+no694q0yf47W5qKkel1i94uFVzZNekPsE4y0OU9Im/5kOY11nHI/XcO/0SZxRGpK0ij7wqu7N9zgOGBTxQWgcJ+7jHZVw0j/f9dDIBxJWI7ik47yahDxPfBOOhHjVB3qeeqRMFfsCWPZfzeeifoDKxeG4kbVEoxCZwRDaZ/uUY9e05BNJ6FhPBuzCOV/ThgUWFSHE6xa+mCm6rEcnhUOWlcFomyR1Xg6o1nFZAx+PsZVxZXQMM6B30XaktQjxufgFF/0hI9dDsIjuzYr0BUSRy8LxT7BUXRSwIuxBnPqMrZ34tE7UjeIe+xRDr+HaEsZ+P3hhhCY0ZlidGlGRJXxX1LCnfHK4zRejlSbyYmIwtdE1AKoWJ1meIwzHgUjW7i+XVeO3IxS4Hbt9Q0VeP4TFastEi3r1cV9kqbnAU="
    # DOCKER_PASSWORD
    secure: "oeeScBpB/pFJLHOlg8hrjuYwjG3ux4ZpcuCKU/v+dbThG82cgsIfhAczXAqJHyRDwWtgvkCTCxCn3Hb9yhVew8gDTM/jEhljrfnevLlHFCexbK1eNem19YiRfdwn9W/YSqr/pF6w1YKDCtRi24LspQj4yCy0Bb3BJB80y0qbsiyMkDjQnDNBQ52sGktxKJMDCd/WQ5NPLOQvS+CLk0n6qXtvjk+iE1RmHJ8tTM/Dk7XxVSYVxvL/QXkFKE+0qWmZCjQGZIyBjBq+vxYTRennQAbNKt+V0+BVu+sBeyt3F8M9FlLKXcI+9L4M8cP5wKg5TaBhpp0KIctfHy6QbaRX2phf9wyzfMS9V77eSixCSHCkg6T74Ohl7Fo7jehLMuIglRzSPqCihG1P+u/tnv/bj3ULfb5op5Fd3+TMyVmqT95qbYkod/iCQYzIE6S2KRahb/AflAQu5hilLOalsOIA4cNt3Vo7REbrqVgGaYcmMKBuVTekQNT+VAkO/JH/Q++w+MtiNW9yJg2oE5vFmjAcWEknwrkwejEwAePxuB9aGn9ZLAXtJLollxhFtRC7QcK84KcVG720mvAidaIwrWgDOCQ+K9smbRMlrdjOwRQSS3wq8RvoMPgJyYYKutK8N+htk1qiBdD4NZxiXemkVRVdQM/+0WgAjcJWZ1SzLl99JBQ="

install:
- pip install tox coveralls

script: tox

after_success:
- coveralls

deploy:
- provider: script
  script: make ci-push
  on:
    branch: master
