language: python

python:
- 3.6

services:
  - docker

env:
  matrix:
  - TOXENV="py${PYTHON_VERSION//./}"
  global:
    # DOCKER_USERNAME
    secure: "yIOx/ex5Nl7F0sFTh+VRDGx6H2n8TeuKpJt6stTqd5jqU9Wc36h4XyA9wCeCuDtev7L3cj0uqCK3F8PddmjpwGRRa4TS8/xTUo7MiH/8Dyk1Cs2CDe4K+UVZqHDa07g7PjH9kP/lWUcNi4p/emdcNgZtDsyTWq4LbIK6ZcPACmO3QRPAdlpxg5yJjVfBymoQVNq8JE+X8WUwnR+roiYrMEnRT/9FAwEv6KzXV2crqSyLx3hCY4hBfD4TR6/TFKAvVLKdNvtJh0eOKHtEgL0BdhSspYPW/8tOuAP3ZOoF+SFoBLIqLKIG4RbpCTDh2m75/liT9q0TdyiMk3mV48PvhBT6aEE4jcX0aKMRBXZii2YbSqdH+o5ae0IZxayS4AuzNzAgxqX+CG0/2wstoonCuFRgY5uTDnOQb94z5teOr+8Rwk0h/QYROK70BJUoR8UVNaRUN/uRogXCN0miGcidt9xkWXZvBoNIHy0EACOZVCka2EEuQd8iDtQh/rp4KLtFrcpJq9rfcWJCqFENhCmfgtHKqHKaTiqrUF0z9poyU0sNXerLU8TTe6gEvlv6njqpo5V59852AV/F4swYkgEkAKce3fEGka23Jzff1Jy+ahtWrNXAZtDJE6KXGHewP4bh1iKM9i0cOVs7fA2A/e6Odlh4ee8Q+MpXt5X1IdTIZHQ="
    # DOCKER_PASSWORD
    secure: "oeeScBpB/pFJLHOlg8hrjuYwjG3ux4ZpcuCKU/v+dbThG82cgsIfhAczXAqJHyRDwWtgvkCTCxCn3Hb9yhVew8gDTM/jEhljrfnevLlHFCexbK1eNem19YiRfdwn9W/YSqr/pF6w1YKDCtRi24LspQj4yCy0Bb3BJB80y0qbsiyMkDjQnDNBQ52sGktxKJMDCd/WQ5NPLOQvS+CLk0n6qXtvjk+iE1RmHJ8tTM/Dk7XxVSYVxvL/QXkFKE+0qWmZCjQGZIyBjBq+vxYTRennQAbNKt+V0+BVu+sBeyt3F8M9FlLKXcI+9L4M8cP5wKg5TaBhpp0KIctfHy6QbaRX2phf9wyzfMS9V77eSixCSHCkg6T74Ohl7Fo7jehLMuIglRzSPqCihG1P+u/tnv/bj3ULfb5op5Fd3+TMyVmqT95qbYkod/iCQYzIE6S2KRahb/AflAQu5hilLOalsOIA4cNt3Vo7REbrqVgGaYcmMKBuVTekQNT+VAkO/JH/Q++w+MtiNW9yJg2oE5vFmjAcWEknwrkwejEwAePxuB9aGn9ZLAXtJLollxhFtRC7QcK84KcVG720mvAidaIwrWgDOCQ+K9smbRMlrdjOwRQSS3wq8RvoMPgJyYYKutK8N+htk1qiBdD4NZxiXemkVRVdQM/+0WgAjcJWZ1SzLl99JBQ="

install:
- pip install tox coveralls

script: tox

after_success:
- coveralls

deploy:
- provider: script
  script: make ci-push
  on:
    branch: master
