version: '2'

services:
  agent:
    build: .
    environment:
      REPO_AGENT_BASE_DIR: /app/source-specs
      REPO_AGENT_BROKER: redis://redis:6379/10
      REPO_AGENT_REPOS: "https://github.com/brew/example-source-spec,
                       /Another/nonexistent/path/repo,
                       https://example.com/example-repo.git"
      REPO_AGENT_UPDATE_FREQUENCY: 15
    volumes:
      - ~/src/dockerfiles/agent:/app/source-specs

  redis:
    image: "redis:3"
